- opening_hours.js
- test.js
> Support for US holidays, tests. Washington DC not working.

- demo.html
Changed onKeyPress to onKeyUp. Might have fixed #15?
> Prettified value updates quicker using OnKeyUp

- opening_hours.js
- test.js
Added holidays and tests for Czech Republic
(hopefully in *correct* fashion)
> Holidays in Czech Republic

- package.json
I updated the package. Also I used a pre-release version. Hope that is okay.
> Node Package Update

- .gitignore
- Makefile
- package.json
This run browserify to build a file containing opening_hours plus all
dependencies to be used in websites.
The I18n part has to be done …
> Add opening_hours+deps.js target

- PH_SH_exporter.js
- interactive_testing.js
- opening_hours.js
Check the two commented lines. You might want to comment them out.
> added danish holidays

- opening_hours.js
When loading through nodejs you can actually also check for moment and Suncalc not to load them twice
> test if moment, Suncalc already exist

- opening_hours.js
> Added NL PH

- css/table.css
added some separators for hours in time table.
additional simplifie some css-rules
> Made the time table look prettier (per hour marks) and CSS cleanup

- locales/core.js
fix korrigiert diverse kleine Rechtschreibfehler
> some small typos

- css/main.css
- index.html
- js/i18n-resources.js
2. add some styles
ich habe die Beschreibungen für die checkboxen mit spans umgeben
auswahl zeit +/- unterhalb der datumseingabe gesetzt (synchron zu den anderen Eingaben)
die Beschreibungen dezent anders gefärbt
Beschreibungen konsequent über die inputboxen gesetzt
P.s. ich bekomme es auf der Webseite irgendwie nicht hin 3 Datein in ein PR zu packen, daher 3 PRs ...
> Add some styles

- css/main.css
- index.html
- js/helpers.js
move spans into js for w3c-compatibility
add spans for descriptions "status" and rules
move inline styles from code to css-file
add css-rules
> add spans, reorder css

- .travis.yml
- Makefile
- bower.json
- package.json
- test.js
Finally all test framework dependencies on my local setup should be resolved and commits can independently and automatically be tested.
Works for me. Does it work for you? :wink:
> Enable CI testing on Travis CI with support matrix NodeJS v0.12.3 to latest

- holidays/gb.yaml
- holidays/index.js
- index.js
Converted from JSON file from #162 (credits to @skifans). Closes #162.
> Add holiday dates for England and Wales

- index.js
> Fix for...in loops for old browsers

- holidays/au.yaml
Created public holiday data for Australia.
yaml code for use in opening_hours.js/holidays
> Created PH for Australia

- CHANGELOG.rst
- README.md
- holidays/ci.yaml
- holidays/index.js
- holidays/nominatim_cache/ci.yaml
- index.js
@sommerluk please have a look.
Refer to #262 for details.
> Add Ivory Coast (CI) PH definition

- taginfo.json
- taginfo_template.json
The existing icon_url is unavailable.
> fix taginfo.json's icon_url

- holidays/fi.yaml
Hi there and thanks for the good work!
It would be great to have the public holidays for Finland as well, these are pretty much the same as for Sweden, apart from independence day, and different naming of holidays. I hope the enclosed file can be helpful in this.
Cheers,
Juho
> Add fi.yaml based on be.yaml, se.yaml examples

- holidays/fr.yaml
Add SH definition  (and some PH) for France.
I'm not familiar with the yaml syntax, nor with Github.
I hope I don't make too many mistakes.
> Ph sh france

- README.md
- index.js
Set optional_conf_parm.additional_rule_separator to false.
Needed for https://josm.openstreetmap.de/ticket/18577
> Allow to disable additional_rule_separator

- README.md
Hey,
Thanks for the awesome library!
When trying to use it, I got a little stuck while reading the docs about the nominatim-object, so I improved them. _Please doublecheck_, as I'm not sure that everything is 100% correct.
Furhtermore, I've started to use the lib in MapComplete to show opening hours. This PR also adds MapComplete as user.
(The following screenshot is a WIP and not live yet, but close to the final OH-display)
> Update of readme: better explanation of nominatim-object, add MapComplete as downstream user of the lib

- examples/simple_index.html
- locales/opening_hours_resources.yaml
Rework for better understanding and better access for beginners.
> Rework simple_index.html

- css/main.css
Proposal to resolve issue #347.
A different look for the read-only fields so that they differ from the writable fields.
> A different look for the read-only fields

- examples/simple_index.html
- js/countryToLanguageMapping.js
I think taking the language for the warnings from the browser setting is nice, but I'm not sure if this is good for a simple example.
> Little fixes and warning language depending from browser

- holidays/fr.yaml
Cleanup of: #353
I squashed the commits into one and restored the history.
> Update SH France

- CHANGELOG.rst
- README.md
- package.json
That already happened with #250, but it wasn't complete.
> Replace moment.js with Date.toLocaleString

- locales/word_error_correction.yaml
Add Italian translations for days, months and seasons
> Add Italian

- package-lock.json
- package.json
- site/index.html
Introduced in: a86fb22e70f2f75860db7502ce7a0ea4e99caf6c, #385
> fix: Only include self hosted resources or use Subresource Integrity

- .eslintrc.js
- package.json
- types/.eslintrc.json
- types/index.d.ts
Hello,
This is probably not the best implementation, usually I use typescript definition auto-generate, but he's lost here :S
To test this, I've use `yarn add https://github.com/MerlinPerrotLegler/opening_hours.js.git#feature/typescript-definition` after having remove 'husky' from the `package.json` (as for some reason it's not working with either yarn or mac).
If I forgot something let me know :)
> #297 Typing for typescript

- Makefile
> chore: Add reminder to create release on GitHub releases page

- src/locales/opening_hours_resources.yaml
I have added italian translation for a couple of terms.
> Added italian translation

- src/locales/opening_hours_resources.yaml
Review all french translations. Better translation.
> Review french translations

- LICENSES/AGPL-3.0-only.txt
- LICENSES/CC0-1.0.txt
- LICENSES/LGPL-3.0-only.txt
=== Do not change lines below ===
{
"chain": [],
"cmd": "rm LICENSES/AGPL-3.0-only.txt && reuse download --all",
"exit": 0,
"extra_inputs": [],
"inputs": [],
"outputs": [],
"pwd": "."
}
^^^ Do not change lines above ^^^
> chore: [DATALAD RUNCMD] add missing license files; redownload

- README.md
Add Public Holidays wiki link on README
> Add Public Holidays wiki link on README

- CHANGELOG.rst
- README.md
- scripts/PH_SH_batch_exporter.sh
- site/index.html
- src/holidays/README.md
- taginfo.json
- taginfo_template.json
This is the preparation for the change. See #494.
> chore: change default git branch from `master` to `main`

- src/holidays/nominatim_cache/xa.yaml
Without this, there was an error running `make check-full`.
> fix: add missing `country_code` to `xa.yaml`

- Makefile
- package-lock.json
- package.json
Since the update of `package-json-validator` made two more little changes necessary, I created this separate PR.
> chore: update `package-json-validator`

- examples/simple_index.html
- improve "input string" comment
- improve code consistency
- optimize console outputs
```
21:47:01.634 Input value (de en mixed): Mo-Tu,Do-Fr 10:00-20:00; Samstag und Sonntag geschlossen simple_index.html:30:15
21:47:01.637 Prettified value (de):     Mo-Di,Do-Fr 10:00-20:00; Sa,So geschlossen simple_index.html:31:15
21:47:01.637 Prettified value (en):     Mo-Tu,Th-Fr 10:00-20:00; Sa,Su off simple_index.html:32:15
21:47:01.637 Prettified value (ru):     пн-вт,чт-пт 10:00-20:00; сб,вс закрыто simple_index.html:33:15
21:47:01.637 Warnings:[
"Mo-Tu,Do <--- (Please use the English abbreviation \"Th\" for \"do\".)",
"Mo-Tu,Do-Fr 10:00-20:00; Samstag <--- (Please use the English abbreviation \"Sa\" for \"samstag\".)",
"Mo-Tu,Do-Fr 10:00-20:00; Samstag und <--- (Please use notation \",\" for …
```
> refactor: optimize `simple_index.html`

- CHANGELOG.rst
- CONTRIBUTING.md
- README.md
As talked about in PR #483, here is a PR to define a branching model. My suggestion is a simplified Gitflow model.
> docs: move Contributing section from README to CONTRIBUTING file and add "Branching Model" section
