opening_hours.js
Added also the code to calculate firstSundays and firstSeptemberSunday
=> Added italian Public Holidays to opening_hours.js

PH_SH_exporter.js, README.md, opening_hours.js
Adding Public Holidays for Romania.
Tests:
```
$ ./PH_SH_exporter.js --verbose --from=2015 --until=2015 --public-holidays --country 'ro' --region 'ro' /tmp/ro_holidays.txt
20150101 Anul Nou
20150102 A doua zi de Anul Nou
20150124 Ziua Unirii Principatelor Române (Ziua Unirii)
20150412 Paștele ortodox
20150413 A doua zi de Paște ortodox
20150501 Ziua Muncii
20150601 Rusaliile
20150602 A doua zi de Rusalii
20150815 Adormirea Maicii Domnului
20151130 Sfântul Apostol Andrei
20151201 Ziua Națională (Ziua Marii Uniri)
20151225 Crăciunul
20151226 A doua zi de Crăciun
$ ./PH_SH_exporter.js --verbose --from=2016 --until=2016 --public-holidays --country 'ro' --region 'ro' /tmp/ro_holidays.txt
20160101 Anul Nou
20160102 A doua zi de Anul Nou
20160124 Ziua Unirii Principatelor Române (Ziua Unirii) …
```
=> Adding Public Holidays for Romania

opening_hours.js
Since 2016, Good Friday (Velký pátek) was approved as public holiday in Czech Republic.
=> Add new PH in Czech

css/table.css
rewrite of https://github.com/opening-hours/opening_hours.js/pull/148
Fix broken time-lines on 2-line-breaks in time table,
add colors for unknown
Bei zweizeiligen Werten im OH-wert wurden die Stunden-Linien durch unsichtbare und/oder fehlende Border zerschnitten. (Bedingt durch die dann höhere leere Box)
=> Fix CSS for joined times.

locales/core.js, opening_hours.js
Added AMD bindings as mentioned in #151. However, there are two drawbacks:
- AMD doesn't support optional dependencies, so _moment_ and _i18next-client_ have to be defined.
- The solution lacks full backwards compatibility. If someone used opening_hours in a browser with AMD modules such as RequireJS but did not define _suncalc_, _moment_ or _i18next-client_ the code will break.
I didn't see tests for module.exports so I didn't add tests for AMD bindings.
=> Introduced AMD.

package.json
The version was fixed and is now more relaxed. That allows better co-existence/merge with other modules that also use `momentjs`
=> Relax version on moment optionalDependency

css/table.css
add width for first table row in weekly-table
beim wechsel von "aug" zu "sept" und/oder von "31" zu "1" sprang die auswerte-grafik um einige pixel (durch breitenänderung der ersten Spalte)
behoben durch feste Breite in Prozent.
=> remove gap-switch in table on changing date

locales/core.js, opening_hours.js
I found a typo: "defintion" instead of "definition". Fixed.
=> Fix typo (defintion -> definition)

opening_hours.js
Addded to getMovableEventsForYear(): nextWednesday16Nov
and used it in the public holiday list for Germany, Sachsen
see https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland#Bewegliche_Feiertage
=> +Holiday: Buß- und Bettag (Germany, Sachsen)

CHANGELOG.rst, locales/word_error_correction.yaml, test.de.log, test.en.log, test.js
=> Input tolerance: Don’t prefer `on appointment` over `by appointment`

.travis.yml, CHANGELOG.rst, package.json
It seems that rollup was updated and now does not work with 0.12.x
anymore.
https://travis-ci.org/opening-hours/opening_hours.js/jobs/354818972
=> Increase NodeJS version requirement to `4.0.0`

index.html
gives direct number keyboard on mobile
also added step, min, max
=> added type=number for input elements

index.html
Giving a mobile browser a hint that this page should not be rendered with a virtual viewport but native.
The mode input element with its long content should not blow up the page width. on mobile the drop down is shown with an own layer so we do not loose many information with this change
BTW will you accept PRs which replaces document.write to logic which uses proper DOM API or innerHTML?
document write blocks rendering and defeats browser optimisations with parsing the initial html
=> Minimal mobile browser support

holidays/de.yaml
Since this year, Reformationstag is also a public holiday in Bremen, Schleswig-Holstein, Niedersachsen and Hamburg.
=> Add new states for PH Reformationstag

README.md
Issuestats.com is gone, now taken over by a spammer.
=> Remove discontinued Issuestats from README

holidays/it.yaml
According to both the [Italian government website](http://presidenza.governo.it/ufficio_cerimoniale/cerimoniale/giornate.html#festivita) and [Wikipedia](https://it.wikipedia.org/wiki/Giornata_dell'Unit%C3%A0_Nazionale_e_delle_Forze_Armate#Storia) _Festa dell'unità nazionale_ is not a public holiday. It has been, but in 1977 it was removed (Wikipedia).
=> Removed non public holiday.

Makefile, package.json
> terser is a fork of uglify-es that mostly retains API and CLI compatibility with uglify-es and uglify-js@3.
=> build: replace uglify-js with terser

holidays/index.js, holidays/xa.yaml
For @JOSM, we only use `opening_hours.js` in order to validate the syntax, but do not compute whether a date is a public/school holiday. Thus, one could strip all country data and just keep a bare minimum dataset in terms of a user-assigned code ISO 3166-1 alpha-2 `XA`.
=> Add holidays for virtual XA country

holidays/us.yaml
Virginia [has replaced](https://www.cnn.com/2020/04/12/politics/virginia-election-day-holiday-early-voting/index.html) Lee-Jackson Day with Election Day as of 2020. I copied the definition of Election Day from another state, but I haven’t checked if it correctly captures the nuance of “Tuesday after the first Monday of November” (e.g., November 8, 2022).
=> Replace Lee-Jackson Day with Election Day

holidays/ro.yaml
Add holidays as far as already known. Summer vacation end is not yet determined yet, see source
https://www.edu.ro/ordinul-ministrului-educa%C8%9Biei-%C8%99i-cercet%C4%83rii-nr-31252020-privind-structura-anului-%C8%99colar-2020-2021
=> add Romanian school holidays 2020-2021

package.json
Build step must be run by npm before publishing.
According to this article, its usually best at the `prepare` hook of npm:
https://itnext.io/step-by-step-building-and-publishing-an-npm-typescript-package-44fe7164964c
> prepare will run both BEFORE the package is packed and published, and on local npm install. Perfect for running building the code. Add this script to package.json
```json
"prepare" : "npm run build"
```
Official npm documentation also has an article on `prepare`: https://docs.npmjs.com/cli/v6/using-npm/scripts#prepare-and-prepublish
I verified this method by:
1. `npm install git+https://github.com/fodor0205/opening_hours.js.git` in an npm project
2. building the same code, that built successfully with the v3.5.0 version currently published on npm
3. the functionality worked …
=> Build package during prepare

package.json
Just noticed that the main path in package.json is wrong given we moved the built files in #372
=> fix: correct main path in package.json

types/index.d.ts
Fixes `ng build` error: `error TS1038: A 'declare' modifier cannot be used in an already ambient context.`
As far as I know, the `declare` operator is not necessary when already inside a `declare module`.
After removing the unnecessary declarations, Angular builds without errors.
@MerlinPerrotLegler maybe you could take a look at it since you wrote the original definition? Don't want to break something that I'm unaware of.
=> Fix TypeScript definition

src/holidays/ro.yaml
Hi, I finally got around to add missing vacation dates for Romania in 2021. 
Source used: https://www.edu.ro/structura_anului_scolar_2021_2022
=> add Romanian SH for summer and winter vacation 2021

site/css/main.css, site/index.html
Set the page’s `lang` attribute dynamically depending on the localization. The browser automatically adapts the quotation marks around the `<q>` tag according to the page language, so there’s no need to hard-code German punctuation for all languages.
=> Set page language dynamically

src/index.js
In MapComplete, it is possible to show opening hours for any tag. When a new key is passed (e.g. access:conditional:motorvehicle), this crashes the evaluator instead of defaulting to `oh_mode=0`.
This patch checks that osm_tag_defaults[oh_regex_key] exists
=> Add check: don't crash if osm_tag_defaults[oh_regex_key] is undefined

types/index.d.ts
The return type of  `opening_hours.getOpenIntervals` was declared as a tuple with two intervals instead of an array of intervals.
The `start_date` parameter of `opening_hours.isEqualTo` was declared as an `opening_hours` object instead of a `Date` object or undefined.
This PR fixes these errors.
=> Fixed some TypeScript types

types/index.d.ts
The documentation mentions that the prettifyValue function takes an optional argument.
> The function accepts an optional hash.
This PR fixes the typescript description to reflect the documentation.
=> fix prettifyValue typescript description

src/holidays/ar.yaml, src/holidays/index.js
https://www.argentina.gob.ar/interior/feriados-nacionales-2022 used as reference.
=> Added basic Argentina holidays

types/index.d.ts
Typescript, make optional_conf.mode optional, as in doc
Solve #428
=> Typescript, make optional_conf.mode optional, as in doc #428

site/js/helpers.js
1. `https` is not working for me
2. iD also uses http instead of `https`
3. The [documentation](https://wiki.openstreetmap.org/wiki/JOSM/RemoteControl) only mentions `http`
=> Switch to http for JOSM

CHANGELOG.rst, site/css/main.css, site/js/helpers.js
To fix #464 I optimized the layout of the error and warning messages a bit.
|   | **before**  | **after**  |
|---|---|---|
| **Error**  | ![error_before](https://github.com/user-attachments/assets/1857a706-8068-4c87-9b26-e56cb1919f45) | ![error_after](https://github.com/user-attachments/assets/2e7b9592-6995-4836-9957-f5f92037348e) |
| **Warning** | ![warning_before](https://github.com/user-attachments/assets/dc761f0e-f3da-4978-9da4-81e837376242) | ![warning_after](https://github.com/user-attachments/assets/7c0e5d96-6ccf-4348-b8a0-e923513cbd35) |
| **Warning prettified length** | ![warning_prettified_length_before](https://github.com/user-attachments/assets/23ec4d74-c3bd-4186-aefd-b63a4ac1bc94)  |  ![warning_prettified_length_after](https://github.com/user-attachments/assets/33077199-2e80-4 …
=> [Evaluation tool] Optimize "Error and warning messages" layout

README.md
triggered by https://github.com/streetcomplete/StreetComplete/pull/5354
=> try to clarify 24/7 description

.husky/pre-commit
They cause too many issues. Developers will need to manually add changed test logs. If they forget, the CI will catch it.
=> chore: drop the `git stash` and `git add` magic from commit hook

types/index.d.ts
This allows calling `switch (it.getStateString())` without needing to handle `"closed"` or `switch (it.getStateString(undefined, true))` without needing to handle `"close"`.
=> Overload `getStateString` for better return type

README.md, src/holidays/gb.yaml, src/index.js
Hi, I've added public holiday definitions for Scotland and Northern Ireland following the existing examples.
When creating these, I ran into a couple of things I wasn't sure how to deal with. These may be larger issues which could be saved for a different pull request.
1. In 2022 only, there's a UK-wide public holiday for the Queen's Diamond Jubilee. I couldn't spot another example of a one year only public holiday so didn't include it for now.
2. I wasn't sure the best way to handle substitute bank holidays. In the UK whenever a bank holiday would fall on a weekend, it gets moved to the next available weekday. There were some examples of this already happening (with the `nextMo-Fr17March` syntax). However I would have expected it to occur for every holiday (including Christmas, etc.). In …
=> Add Scotland and Northern Ireland public holidays

CHANGELOG.md, src/holidays/de.yaml
It is public holiday since 2023 there. Source: https://de.wikipedia.org/wiki/Feiertag_(Deutschland)
=> feat(DE): update Frauentag states to include Mecklenburg-Vorpommern

CHANGELOG.md, test/test.de.log, test/test.en.log, test/test.js
Replace hardcoded English expected strings with locale-dependent variable. This reduces failing (german) tests from 51 to 10.
=> fix: localize expected test strings for German locale

CHANGELOG.md, src/index.js, test/test.de.log, test/test.en.log
Replace day-of-month comparison with full date comparison in `parseWeekdayRange` function for constrained weekdays with `add_days`.
The previous implementation only compared the day number (`getDate()`) instead of the complete date, causing incorrect matches when the target date falls in a different month than the current date.
For example, "Sa[-1] +3 days" in August 2013:
- Last Saturday of August: August 31
- August 31 + 3 days: September 3
- Previously matched September 1 (day 1) instead of September 3
The corresponding test, which previously failed, now works with the fix.
=> fix: use full date comparison for constrained weekday matching

CHANGELOG.md, package-lock.json, package.json, scripts/PH_SH_exporter.js, scripts/gen_taginfo_json.js, scripts/interactive_testing.js, test/test.js
I could only use version 17 of yargs, as version 18 is ESM only. We'll take care of converting the scripts to ESM another time :slightly_smiling_face:
=> refactor: replace deprecated `optimist` with `yargs` for command line argument parsing

CHANGELOG.md, Makefile, scripts/regex_search.py
About the second commit:
Since `pyopening_hours` cannot be installed at the moment (see https://github.com/opening-hours/pyopening_hours/issues/3), the script still does not work.
The intention of the commit is to ensure that no one is distracted by syntax errors and that the main problem is immediately clear.
=> fix: update script paths, use python for regex search execution and update syntax in `regex_search.py`
